# In-Class Programming Activity, Day 4
```{r}
library(ISLR)
```

##Task 1
```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")
```

##Task 2
```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")


x1=c(60,20)
y1 = c(20,60)

x2=c(20,20)
y2 = c(60,60)
points(c(x1[1],y1[1]),c(x1[2],y1[2]),pch=9)
points(c(x2[1],y2[1]),c(x2[2],y2[2]),pch=9)

lines(x1,x2)
lines(y1,y2)

plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")
x2=c(60,20,20,60,60)
y2 = c(20,20,60,60,20)
points(c(x2[1],x2[2],x2[3],x2[4]),c(y2[1],y2[2],y2[3],y2[4]),pch=9)
lines(c(x2[1],y2[1]),c(x2[2],y2[2]))
lines(c(x2[2],y2[2]),c(x2[3],y2[3]))
lines(c(x2[3],y2[3]),c(x2[4],y2[4]))
lines(c(x2[4],y2[4]),c(x2[5],y2[5]))

```

## Task 3
```{r}
options(digits=6)
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")
angles=seq(0,2*pi,by=0.001)
x3=20*cos(angles)+50
y3=20*sin(angles)+60
points(x3,y3,pch=1)
```

## Test 4
```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")
angles=seq(0,2*pi,by=0.001)
x4=20*abs(sin(angles))*round(cos(angles),digits=6)
y4=20* abs(sin(angles))*round(sin(angles),digits=6)
polygon(x4+50,y4+60)
       
```

## Task 5
```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n",ylab="y axis", xlab="x axis",xaxt ="n")
points(c(50,30,70),c(60,60,60),col = col2rgb('tomato', alpha = .1),pch=4)

```
## Test statements

```{r}
scoreActivity::score253(4)
```