# In-Class Programming Activity, Day 8

#Task 1
```{r}
x = runif(100, min=20,max=70)
y = 5+3*x + 2*rnorm(100)
My_data=data.frame(x=x,y=y)
plot(My_data)

LL_line<-function(params){
  sum(log(dnorm(y - (params[1] * x + params[2]), sd = params[3])))
}

paramA=c(3,5,2)
paramB=c(4,1,10)
testA = LL_line(paramA)
testB = LL_line(paramB)
starting_params <- c(4, 1, 10)
best <- optim(starting_params, LL_line, control=list(fnscale = -1))
```

#Task 2
```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))
NYTaxis <- Taxi_trips


taxi_likelihood <- function(P) {
  base_fare <- P[1]
  per_mile <- P[2]
  params <- P[3]
  waiting_fare <- NYTaxis$fare_amount - (base_fare + per_mile*NYTaxis$trip_distance)
   return(sum(log(dexp(waiting_fare, rate = params) + 0.001)))
}
starting_params=c( 2.00, 4.00, 1/3)
best <- optim(starting_params, taxi_likelihood, control=list(fnscale = -1))
plot(NYTaxis$trip_distance,NYTaxis$fare_amount,xlab='trip distance',ylab='')

P = best$par
abline(P[1],P[2],col='blue',lwd=3)
```

```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))
```
## Test statements

```{r}
scoreActivity::score253(8)
```