# In-Class Programming Activity, Day 15

```{r}
load('mona.rda')
X <- t(mona) - mean(mona[])
X_rand = matrix(rnorm(length(X),mean=0,sd=1),nrow=nrow(X),ncol=ncol(X))
X_corr=X_rand%*%chol(var(X))
```

#Sparse Beta
```{r}
beta=rep(0,191)
n=sample(1:191,175)
beta[-n]=sample( c(2, 5, -3,-4) ,16,replace=TRUE)
```

#The output
```{r}
Y_pure=X%*%beta
var_Y_real = 0.1*var(Y_pure)
X_rand1 = matrix(rnorm(length(X),mean=0,sd=sqrt(var_Y_real)),nrow=nrow(X),ncol=ncol(X))
Y_real=(X+X_rand1%*%chol(var(X)))%*%beta
```
#Least squares
```{r}
beta_hat_pure=lm(Y_pure~X)$coefficients
plot(beta_hat_pure[-1])
points(beta,pch=4)
beta_hat_real=lm(Y_real~X) 
```

#The lasso estimator
```{r}
library(glmnet)
lasso_mod<- cv.glmnet(X, Y_real, alpha=1)
beta_lasso <- predict(lasso_mod, type = "coefficients", s = lasso_mod$lambda.min)
```
#Principal components
```{r}
sing_vals <- svd(X)$d
approx_X=cumsum(sing_vals^2)/sum(sing_vals^2)

sing_vals_rand <- svd(X_rand)$d
approx_X_rand=cumsum(sing_vals_rand^2)/sum(sing_vals_rand^2)

sing_vals_corr <- svd(X_corr)$d
approx_X_corr=cumsum(sing_vals_corr^2)/sum(sing_vals_corr^2)

n99=sum(approx_X<=0.99)
n99_rand=sum(approx_X_rand<=0.99)
n99_corr=sum(approx_X_corr<=0.99)
library(pls)
pcr.fit <- pcr(Y_real ~ X, scale = TRUE, validation="CV") 
```



## Test statements

```{r}
scoreActivity::score253(15)
```